[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_ALCHEMY_API_KEY,REACT_APP_ETHERSCAN_API_KEY,REACT_APP_SUPABASE_ANON_KEY,REACT_APP_SUPABASE_URL"

# Scheduled Functions - NFT Floor Price Updates
[[functions]]
  name = "update-floor-prices"
  schedule = "0 * * * *"  # Run every hour at minute 0

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200